### ISSUE TITLE
Create official project release via repo

### ISSUE THREAD

**Issue by vcwild** [Thalmonn/cadastrei#1]
Olá Thalmonn, muito bacana seu projeto. 

Vi que você lançou uma release inicial. Você pode disponibilizar ela usando os recursos do próprio GitHub. 

Segue a documentação para tal: 

- [Managing project releases](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository)

**Comment by Thalmonn** [comment]
Oi Victor,

Muito obrigado por verificar e criar a issue.

Corrigido na tag [v0.1.1](https://github.com/Thalmonn/cadastrei/releases/tag/v0.1.1).
