### ISSUE TITLE
Missing project requirements

### ISSUE THREAD

**Issue by vcwild** [Thalmonn/cadastrei#2]
Olá Thalmonn, para que possamos recriar seu ambiente de desenvolvimento, precisamos que você congele suas bibliotecas de requerimentos em um arquivo de **requirements**.

Você pode fazer isso com o seguinte comando no terminal:

```sh
pip freeze > requirements.txt
```

**Comment by Thalmonn** [comment]
Oi Victor,

Obrigado de verdade pelas dicas. A solicitação foi sanada no commit [8ff4e9f](https://github.com/Thalmonn/cadastrei/commit/8ff4e9f9d10250767a38cd28c05a15b6ada49f57).
